### ISSUE TITLE
arduino micro Avr109 not working on java 1.8 or on java 11 

### ISSUE THREAD

**Issue by vospascal** [t2t-sonbui/ArduinoHexUploadExample#2]
``
Info:Starting ArduinoSketchUploader...
COM8
Info:Starting upload process for file '..\Java-ArduinoSketchUploader-master\Hex\Blink.pro.hex'.
Info:Port autoselected: null.
Trace:Creating serial port 'COM8'...
Info:Protocol.Avr109
Info:Establishing memory block contents...
Info:Opening serial port COM8 - baudrate 57600
Info:Executing Post Open behavior (ArduinoUploader.BootloaderProgrammers.ResetBehavior.ResetThrough1200BpsBehavior@4fca772d)...
Info:Issuing forced 1200bps reset...
COM8
COM8
Info:T+0 - Port not found
Info:T+100 - Port not found
Info:T+200 - Port not found
Info:T+300 - Port not found
Info:T+400 - Port not found
Info:T+500 - Port not found
Info:T+600 - Port not found
Info:T+700 - Port not found
Info:T+800 - Port not found
Info:T+900 - Port not found
Info:T+1000 - Port not found
Info:T+1100 - Port not found
Info:T+1200 - Port not found
Info:T+1300 - Port not found
Info:T+1400 - Port not found
Info:T+1500 - Port not found
Info:T+1600 - Port not found
Info:T+1700 - Port not found
Info:T+1800 - Port not found
Info:T+1900 - Port not found
Info:T+2000 - Port not found
Info:T+2100 - Port not found
Info:T+2200 - Port not found
Info:T+2300 - Port not found
Info:T+2400 - Port not found
Info:T+2500 - Port not found
Info:T+2600 - Port not found
Info:T+2700 - Port not found
Info:T+2800 - Port not found
Info:T+2900 - Port not found
Info:T+3000 - Port not found
Info:T+3100 - Port not found
Info:T+3200 - Port not found
Info:T+3300 - Port not found
Info:T+3400 - Port not found
Info:T+3500 - Port not found
Info:T+3600 - Port not found
Info:T+3700 - Port not found
Info:T+3800 - Port not found
Info:T+3900 - Port not found
Info:T+4000 - Port not found
Info:T+4100 - Port not found
Info:T+4200 - Port not found
Info:T+4300 - Port not found
Info:T+4400 - Port not found
Info:T+4500 - Port not found
Info:T+4600 - Port not found
Info:T+4700 - Port not found
Info:T+4800 - Port not found
Info:T+4900 - Port not found
Info:T+5000 - Port not found
Info:T+5100 - Port not found
Info:T+5200 - Port not found
Info:T+5300 - Port not found
Info:T+5400 - Port not found
Info:T+5500 - Port not found
Info:T+5600 - Port not found
Info:T+5700 - Port not found
Info:T+5800 - Port not found
Info:T+5900 - Port not found
Info:T+6000 - Port not found
Info:T+6100 - Port not found
Info:T+6200 - Port not found
Info:T+6300 - Port not found
Info:T+6400 - Port not found
Info:T+6500 - Port not found
Info:T+6600 - Port not found
Info:T+6700 - Port not found
Info:T+6800 - Port not found
Info:T+6900 - Port not found
Info:T+7000 - Port not found
Info:T+7100 - Port not found
Info:T+7200 - Port not found
Info:T+7300 - Port not found
Info:T+7400 - Port not found
Info:T+7500 - Port not found
Info:T+7600 - Port not found
Info:T+7700 - Port not found
Info:T+7800 - Port not found
Info:T+7900 - Port not found
Info:T+8000 - Port not found
Info:T+8100 - Port not found
Info:T+8200 - Port not found
Info:T+8300 - Port not found
Info:T+8400 - Port not found
Info:T+8500 - Port not found
Info:T+8600 - Port not found
Info:T+8700 - Port not found
Info:T+8800 - Port not found
Info:T+8900 - Port not found
Info:T+9000 - Port not found
Info:T+9100 - Port not found
java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at ArduinoUploader.BootloaderProgrammers.WaitHelper.WaitFor(WaitHelper.java:42)
	at ArduinoUploader.BootloaderProgrammers.ResetBehavior.ResetThrough1200BpsBehavior.Reset(ResetThrough1200BpsBehavior.java:66)
	at ArduinoUploader.BootloaderProgrammers.ArduinoBootloaderProgrammer.Open(ArduinoBootloaderProgrammer.java:62)
	at ArduinoUploader.ArduinoSketchUploader.UploadSketch(ArduinoSketchUploader.java:215)
	at ArduinoUploader.ArduinoSketchUploader.UploadSketch(ArduinoSketchUploader.java:113)
	at Test.Test.main(Test.java:71)
ArduinoUploader.ArduinoUploaderException: Exception during close of the programmer: 'Task java.util.concurrent.FutureTask@7e6cbb7a rejected from java.util.concurrent.ThreadPoolExecutor@7c3df479[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]'.
	at ArduinoUploader.BootloaderProgrammers.Protocols.AVR109.Avr109BootloaderProgrammer.Close(Avr109BootloaderProgrammer.java:50)
	at ArduinoUploader.ArduinoSketchUploader.UploadSketch(ArduinoSketchUploader.java:260)
	at ArduinoUploader.ArduinoSketchUploader.UploadSketch(ArduinoSketchUploader.java:113)
	at Test.Test.main(Test.java:71)
Info:Closing COM8...
Info:Waiting for virtual port COM8 to disappear...
COM8
Error:Exception during close of the programmer: 'Task java.util.concurrent.FutureTask@7e6cbb7a rejected from java.util.concurrent.ThreadPoolExecutor@7c3df479[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]'.

Process finished with exit code 0
``

i converted it to java modules that doesnt change much it still doenst work same as your java lib.
i think it has to do with the pro micro / ATmega32u4 code when it goes in to ResetThrough1200BpsBehavior class
i saw some people using your nice library saw a demo https://www.youtube.com/watch?v=MbZ_SWYXUH4
as you see the logger with progress is also not working sadly.

you have any idea wy how i could get it going or what is wrong 

Kind regeards Pascal

**Comment by georgedrive** [comment]
I have the same problem

**Comment by t2t-sonbui** [comment]
Well, I haven't tried it yet, so if you can fix it, please share it

**Comment by georgedrive** [comment]
It doesn't read the signature... and that's why it doesn't work. Understand in more detail lack of experience

**Comment by georgedrive** [comment]
It doesn't read the signature... and that's why it doesn't work. Understand in more detail lack of experience

**Comment by georgedrive** [comment]
the correct command is sent to the signature request - the current in the response all sorts of random numbers come

**Comment by vospascal** [comment]
Yea I tried multiple things but it disconnects because it goes in bootloader mode or something and the comport changes and then it timeout. Also I’m not a Java expert but think there some ways to clean up the code using lambda and or other waiting mechanism if you convert it to java modules and recent version of java.

**Comment by vospascal** [comment]
I did get the nano to work

**Comment by georgedrive** [comment]
Nano does not use AVR109 protocol!!!

**Comment by georgedrive** [comment]
Claims about protocol problems avr109 and not 500

**Comment by georgedrive** [comment]
I have Nano v3 (Stk500v1) perfectly flashed, but Leonardo (Avr109) is not flashed

**Comment by t2t-sonbui** [comment]
Yes, try with the https://github.com/twinearthsoftware/ArduinoSketchUploader and make a compare

**Comment by georgedrive** [comment]
D:\Work\ArduinoSketchUploader-3.2.0>ArduinoSketchUploader.exe --file=1.hex --port=COM8 --model=Leonardo
2022-07-03 17:42:31.7201|INFO|ArduinoSketchUploader|Starting ArduinoSketchUploader...
2022-07-03 17:42:32.0190|INFO|ArduinoSketchUploader|Starting upload process for file '1.hex'.
2022-07-03 17:42:33.9999|INFO|ArduinoSketchUploader|Establishing memory block contents...
2022-07-03 17:42:34.2309|INFO|ArduinoSketchUploader|Opening serial port COM8 - baudrate 57600
2022-07-03 17:42:34.2309|INFO|ArduinoSketchUploader|Executing Post Open behavior (ArduinoUploader.BootloaderProgrammers.ResetBehavior.ResetThrough1200BpsBehavior)...
2022-07-03 17:42:34.2309|INFO|ArduinoSketchUploader|Issuing forced 1200bps reset...
2022-07-03 17:42:35.0917|INFO|ArduinoSketchUploader|T+0 - Port found: COM9
2022-07-03 17:42:35.0917|INFO|ArduinoSketchUploader|Establishing sync...
2022-07-03 17:42:35.1171|INFO|ArduinoSketchUploader|Sync established.
2022-07-03 17:42:35.1171|INFO|ArduinoSketchUploader|Checking device signature...
2022-07-03 17:42:35.2954|INFO|ArduinoSketchUploader|Device signature checked.
2022-07-03 17:42:35.2954|INFO|ArduinoSketchUploader|Initializing device...
2022-07-03 17:42:35.4038|INFO|ArduinoSketchUploader|Software identifier: 'CATERIN'
2022-07-03 17:42:35.4160|INFO|ArduinoSketchUploader|Software Version: 1.0
2022-07-03 17:42:35.4160|INFO|ArduinoSketchUploader|Programmer type: S.
2022-07-03 17:42:35.4409|INFO|ArduinoSketchUploader|Block support - buffer size 128 bytes.
2022-07-03 17:42:35.5737|INFO|ArduinoSketchUploader|Supported devices: 68.
2022-07-03 17:42:35.5737|INFO|ArduinoSketchUploader|Selecting device type '68'...
2022-07-03 17:42:35.5913|INFO|ArduinoSketchUploader|Device initialized.
2022-07-03 17:42:35.5913|INFO|ArduinoSketchUploader|Enabling programming mode on the device...
2022-07-03 17:42:35.6079|INFO|ArduinoSketchUploader|Programming mode enabled.
2022-07-03 17:42:35.6079|INFO|ArduinoSketchUploader|Programming device...
2022-07-03 17:42:35.6997|INFO|ArduinoSketchUploader|Preparing to write 19126 bytes...
2022-07-03 17:42:35.6997|INFO|ArduinoSketchUploader|Flash page size: 128.
2022-07-03 17:42:35.8706|INFO|ArduinoSketchUploader|Upload progress: 0,0% ...
2022-07-03 17:42:36.1083|INFO|ArduinoSketchUploader|Upload progress: 0,3% ...
2022-07-03 17:42:36.1396|INFO|ArduinoSketchUploader|Upload progress: 0,7% ...
2022-07-03 17:42:36.1704|INFO|ArduinoSketchUploader|Upload progress: 1,0% ...
2022-07-03 17:42:36.2011|INFO|ArduinoSketchUploader|Upload progress: 1,3% ...
2022-07-03 17:42:36.2324|INFO|ArduinoSketchUploader|Upload progress: 1,7% ...
2022-07-03 17:42:36.2631|INFO|ArduinoSketchUploader|Upload progress: 2,0% ...
2022-07-03 17:42:36.2939|INFO|ArduinoSketchUploader|Upload progress: 2,3% ...
2022-07-03 17:42:36.3247|INFO|ArduinoSketchUploader|Upload progress: 2,7% ...


...

2022-07-03 17:42:45.1499|INFO|ArduinoSketchUploader|Upload progress: 48,5% ...
2022-07-03 17:42:45.1807|INFO|ArduinoSketchUploader|Upload progress: 48,9% ...
2022-07-03 17:42:45.2115|INFO|ArduinoSketchUploader|Upload progress: 49,2% ...
2022-07-03 17:42:45.2422|INFO|ArduinoSketchUploader|Upload progress: 49,5% ...
2022-07-03 17:42:45.2730|INFO|ArduinoSketchUploader|Upload progress: 49,9% ...
2022-07-03 17:42:45.3042|INFO|ArduinoSketchUploader|19126 bytes written to flash memory!
2022-07-03 17:42:45.3042|INFO|ArduinoSketchUploader|Device programmed.
2022-07-03 17:42:45.3067|INFO|ArduinoSketchUploader|Verifying program...
2022-07-03 17:42:45.3067|INFO|ArduinoSketchUploader|Preparing to verify 19126 bytes...
2022-07-03 17:42:45.3067|INFO|ArduinoSketchUploader|Flash page size: 128.
2022-07-03 17:42:45.3067|INFO|ArduinoSketchUploader|Upload progress: 50,0% ...
2022-07-03 17:42:45.3809|INFO|ArduinoSketchUploader|Upload progress: 50,3% ...
2022-07-03 17:42:45.4038|INFO|ArduinoSketchUploader|Upload progress: 50,7% ...
2022-07-03 17:42:45.4268|INFO|ArduinoSketchUploader|Upload progress: 51,0% ...
2022-07-03 17:42:45.4493|INFO|ArduinoSketchUploader|Upload progress: 51,3% ...
2022-07-03 17:42:45.4717|INFO|ArduinoSketchUploader|Upload progress: 51,7% ...


....


2022-07-03 17:42:48.5396|INFO|ArduinoSketchUploader|Upload progress: 96,2% ...
2022-07-03 17:42:48.5621|INFO|ArduinoSketchUploader|Upload progress: 96,5% ...
2022-07-03 17:42:48.5845|INFO|ArduinoSketchUploader|Upload progress: 96,8% ...
2022-07-03 17:42:48.6070|INFO|ArduinoSketchUploader|Upload progress: 97,2% ...
2022-07-03 17:42:48.6300|INFO|ArduinoSketchUploader|Upload progress: 97,5% ...
2022-07-03 17:42:48.6524|INFO|ArduinoSketchUploader|Upload progress: 97,9% ...
2022-07-03 17:42:48.6749|INFO|ArduinoSketchUploader|Upload progress: 98,2% ...
2022-07-03 17:42:48.6973|INFO|ArduinoSketchUploader|Upload progress: 98,5% ...
2022-07-03 17:42:48.7198|INFO|ArduinoSketchUploader|Upload progress: 98,9% ...
2022-07-03 17:42:48.7427|INFO|ArduinoSketchUploader|Upload progress: 99,2% ...
2022-07-03 17:42:48.7652|INFO|ArduinoSketchUploader|Upload progress: 99,5% ...
2022-07-03 17:42:48.7877|INFO|ArduinoSketchUploader|Upload progress: 99,9% ...
2022-07-03 17:42:48.8101|INFO|ArduinoSketchUploader|19126 bytes verified!
2022-07-03 17:42:48.8101|INFO|ArduinoSketchUploader|Verified program!
2022-07-03 17:42:48.8101|INFO|ArduinoSketchUploader|Leaving programming mode...
2022-07-03 17:42:48.8360|INFO|ArduinoSketchUploader|Left programming mode!
2022-07-03 17:42:48.8389|INFO|ArduinoSketchUploader|Closing COM9...
2022-07-03 17:42:48.8712|INFO|ArduinoSketchUploader|Waiting for virtual port COM9 to disappear...
2022-07-03 17:42:48.8712|INFO|ArduinoSketchUploader|T+0 - Port still present...
2022-07-03 17:42:48.9781|INFO|ArduinoSketchUploader|T+100 - Port still present...
2022-07-03 17:42:49.0797|INFO|ArduinoSketchUploader|T+200 - Port still present...
2022-07-03 17:42:49.1812|INFO|ArduinoSketchUploader|T+300 - Port still present...
2022-07-03 17:42:49.2828|INFO|ArduinoSketchUploader|T+400 - Port still present...
2022-07-03 17:42:49.3853|INFO|ArduinoSketchUploader|T+500 - Port disappeared: COM9!
2022-07-03 17:42:49.3853|INFO|ArduinoSketchUploader|All done, shutting down!

D:\Work\ArduinoSketchUploader-3.2.0>

**Comment by georgedrive** [comment]
[ArduinoSketchUploader.txt](https://github.com/t2t-sonbui/ArduinoHexUploadExample/files/9034791/ArduinoSketchUploader.txt)

**Comment by vospascal** [comment]
that for micro(Avr109) or nano

**Comment by georgedrive** [comment]
D:\Work\ArduinoSketchUploader-3.2.0>ArduinoSketchUploader.exe --file=1.hex --port=COM8 --model=Leonardo

avr109 Leonardo/micro , nano 500 protocol

**Comment by georgedrive** [comment]
Boards.java

    ARDUINO_NANO_328            ( "na32", McuIdentifier.AtMega328P,     Protocol.Stk500v1
    ARDUINO_NANO_168            ( "na16", McuIdentifier.AtMega168,      Protocol.Stk500v1
    ARDUINO_LEONARD             ( "leon", McuIdentifier.AtMega32U4,     Protocol.Avr109
    ARDUINO_ESPLORA             ( "espl", McuIdentifier.AtMega32U4,     Protocol.Avr109
    ARDUINO_MICRO               ( "micr", McuIdentifier.AtMega32U4,     Protocol.Avr109

**Comment by georgedrive** [comment]
I/MainActivity: Info:Starting ArduinoSketchUploader...
I/MainActivity: Info:Protocol.Avr109
I/MainActivity: Info:Establishing memory block contents...
D/dalvikvm: GC_FOR_ALLOC freed 208K, 8% free 3134K/3400K, paused 4ms, total 4ms
D/dalvikvm: GC_FOR_ALLOC freed 35K, 3% free 3610K/3704K, paused 5ms, total 5ms
D/dalvikvm: GC_FOR_ALLOC freed 120K, 5% free 4001K/4180K, paused 22ms, total 22ms
I/MainActivity: Info:Opening serial port /dev/bus/usb/001/049 - baudrate 57600
I/CDCSerialDevice: Control Transfer Response: 7
I/CDCSerialDevice: Control Transfer Response: 7
I/CDCSerialDevice: Control Transfer Response: 7
I/CDCSerialDevice: Control Transfer Response: 7
I/CDCSerialDevice: Control Transfer Response: 7
I/CDCSerialDevice: Control Transfer Response: 7
I/MainActivity: Info:Executing Post Open behavior (ArduinoUploader.BootloaderProgrammers.ResetBehavior.ResetThrough1200BpsBehavior@528513dc)...
I/MainActivity: Info:Issuing forced 1200bps reset...
I/System.out: deviceKey:/dev/bus/usb/001/049-> UsbDevice[mName=/dev/bus/usb/001/049,mVendorId=9025,mProductId=32822,mClass=239,mSubclass=2,mProtocol=1,mInterfaces=[Landroid.os.Parcelable;@528d7dcc]
I/CDCSerialDevice: Control Transfer Response: 0
D/UsbDeviceConnectionJNI: close
D/dalvikvm: GC_FOR_ALLOC freed 357K, 10% free 4099K/4516K, paused 4ms, total 5ms
I/CDCSerialDevice: Control Transfer Response: 7
I/CDCSerialDevice: Control Transfer Response: 7
I/CDCSerialDevice: Control Transfer Response: 7
I/CDCSerialDevice: Control Transfer Response: 7
I/CDCSerialDevice: Control Transfer Response: 7
I/CDCSerialDevice: Control Transfer Response: 7
I/CDCSerialDevice: Control Transfer Response: 0
I/CDCSerialDevice: Control Transfer Response: 0
I/CDCSerialDevice: Interface succesfully claimed
I/CDCSerialDevice: Control Transfer Response: 7
I/CDCSerialDevice: Control Transfer Response: 0
D/UsbRequestJNI: init
I/CDCSerialDevice: Control Transfer Response: 7
I/CDCSerialDevice: Control Transfer Response: 7
I/CDCSerialDevice: Control Transfer Response: 0
W/System.err: java.lang.InterruptedException
W/System.err:     at java.lang.Object.wait(Native Method)
W/System.err:     at java.lang.Object.wait(Object.java:364)
W/System.err:     at com.felhr.usbserial.SerialBuffer$SynchronizedBuffer.get(SerialBuffer.java:117)
W/System.err:     at com.felhr.usbserial.SerialBuffer.getWriteBuffer(SerialBuffer.java:72)
W/System.err:     at com.felhr.usbserial.UsbSerialDevice$WriteThread.doRun(UsbSerialDevice.java:402)
W/System.err:     at com.felhr.usbserial.AbstractWorkerThread.run(AbstractWorkerThread.java:21)
D/UsbDeviceConnectionJNI: close
I/System.out: deviceKey:/dev/bus/usb/001/049-> UsbDevice[mName=/dev/bus/usb/001/049,mVendorId=9025,mProductId=32822,mClass=239,mSubclass=2,mProtocol=1,mInterfaces=[Landroid.os.Parcelable;@5287db78]
I/MainActivity: Info:T+0 - Port not found
I/MainActivity: Info:T+100 - Port not found
I/MainActivity: Info:T+200 - Port not found
I/MainActivity: Info:T+300 - Port not found
I/MainActivity: Info:T+400 - Port not found
I/MainActivity: Info:T+500 - Port not found
I/MainActivity: Info:T+600 - Port not found
I/MainActivity: Info:T+700 - Port not found
I/MainActivity: Info:T+800 - Port not found
I/MainActivity: Info:T+900 - Port not found
I/MainActivity: Info:T+1000 - Port not found
I/MainActivity: Info:T+1100 - Port not found
I/MainActivity: Info:T+1200 - Port not found
I/MainActivity: Info:T+1300 - Port not found
I/MainActivity: Info:T+1400 - Port not found
I/MainActivity: Info:T+1500 - Port not found
I/MainActivity: Info:T+1600 - Port not found
I/MainActivity: Info:T+1700 - Port not found
I/MainActivity: Info:T+1800 - Port not found
I/MainActivity: Info:T+1900 - Port not found
I/MainActivity: Info:T+2000 - Port not found
I/MainActivity: Info:T+2100 - Port not found
I/MainActivity: Info:T+2200 - Port not found
I/MainActivity: Info:T+2300 - Port not found
I/MainActivity: Info:T+2400 - Port not found
I/MainActivity: Info:T+2500 - Port not found
I/MainActivity: Info:T+2600 - Port not found
I/MainActivity: Info:T+2700 - Port not found
I/MainActivity: Info:T+2800 - Port not found
I/MainActivity: Info:T+2900 - Port not found
I/MainActivity: Info:T+3000 - Port not found
I/MainActivity: Info:T+3100 - Port not found
I/MainActivity: Info:T+3200 - Port not found
I/MainActivity: Info:T+3300 - Port not found
I/MainActivity: Info:T+3400 - Port not found
I/MainActivity: Info:T+3500 - Port not found
I/MainActivity: Info:T+3600 - Port not found
I/MainActivity: Info:T+3700 - Port not found
I/MainActivity: Info:T+3800 - Port not found
I/MainActivity: Info:T+3900 - Port not found
I/MainActivity: Info:T+4000 - Port not found
I/MainActivity: Info:T+4100 - Port not found
I/MainActivity: Info:T+4200 - Port not found
I/MainActivity: Info:T+4300 - Port not found
I/MainActivity: Info:T+4400 - Port not found
I/MainActivity: Info:T+4500 - Port not found
I/MainActivity: Info:T+4600 - Port not found
I/MainActivity: Info:T+4700 - Port not found
I/MainActivity: Info:T+4800 - Port not found
I/MainActivity: Info:T+4900 - Port not found
I/MainActivity: Info:T+5000 - Port not found
I/MainActivity: Info:T+5100 - Port not found
I/MainActivity: Info:T+5200 - Port not found
I/MainActivity: Info:T+5300 - Port not found
I/MainActivity: Info:T+5400 - Port not found
I/MainActivity: Info:T+5500 - Port not found
I/MainActivity: Info:T+5600 - Port not found
I/MainActivity: Info:T+5700 - Port not found
I/MainActivity: Info:T+5800 - Port not found
I/MainActivity: Info:T+5900 - Port not found
I/MainActivity: Info:T+6000 - Port not found
I/MainActivity: Info:T+6100 - Port not found
I/MainActivity: Info:T+6200 - Port not found
I/MainActivity: Info:T+6300 - Port not found
I/MainActivity: Info:T+6400 - Port not found
I/MainActivity: Info:T+6500 - Port not found
I/MainActivity: Info:T+6600 - Port not found
I/MainActivity: Info:T+6700 - Port not found
I/MainActivity: Info:T+6800 - Port not found
I/MainActivity: Info:T+6900 - Port not found
I/MainActivity: Info:T+7000 - Port not found
I/MainActivity: Info:T+7100 - Port not found
I/MainActivity: Info:T+7200 - Port not found
I/MainActivity: Info:T+7300 - Port not found
I/MainActivity: Info:T+7400 - Port not found
I/MainActivity: Info:T+7500 - Port not found
I/MainActivity: Info:T+7600 - Port not found
I/MainActivity: Info:T+7700 - Port not found
I/MainActivity: Info:T+7800 - Port not found
I/MainActivity: Info:T+7900 - Port not found
I/MainActivity: Info:T+8000 - Port not found
I/MainActivity: Info:T+8100 - Port not found
I/MainActivity: Info:T+8200 - Port not found
I/MainActivity: Info:T+8300 - Port not found
I/MainActivity: Info:T+8400 - Port not found
I/MainActivity: Info:T+8500 - Port not found
I/MainActivity: Info:T+8600 - Port not found
I/MainActivity: Info:T+8700 - Port not found
I/MainActivity: Info:T+8800 - Port not found
I/MainActivity: Info:T+8900 - Port not found
I/MainActivity: Info:T+9000 - Port not found
I/MainActivity: Info:T+9100 - Port not found
I/MainActivity: Info:T+9200 - Port not found
I/MainActivity: Info:T+9300 - Port not found
I/MainActivity: Info:T+9400 - Port not found
I/MainActivity: Info:T+9500 - Port not found
I/MainActivity: Info:T+9600 - Port not found
I/MainActivity: Info:T+9700 - Port not found
I/MainActivity: Info:T+9800 - Port not found
I/MainActivity: Info:T+9900 - Port not found
W/System.err: java.util.concurrent.TimeoutException
W/System.err:     at java.util.concurrent.FutureTask.get(FutureTask.java:176)
W/System.err:     at ArduinoUploader.BootloaderProgrammers.WaitHelper.WaitFor(WaitHelper.java:42)
W/System.err:     at ArduinoUploader.BootloaderProgrammers.ResetBehavior.ResetThrough1200BpsBehavior.Reset(ResetThrough1200BpsBehavior.java:68)
W/System.err:     at ArduinoUploader.BootloaderProgrammers.ArduinoBootloaderProgrammer.Open(ArduinoBootloaderProgrammer.java:64)
W/System.err:     at ArduinoUploader.ArduinoSketchUploader.UploadSketch(ArduinoSketchUploader.java:306)
W/System.err:     at xyz.vidieukhien.embedded.arduinohexuploadexample.MainActivity.uploadHex(MainActivity.java:320)
W/System.err:     at xyz.vidieukhien.embedded.arduinohexuploadexample.MainActivity$UploadRunnable.run(MainActivity.java:336)
W/System.err:     at java.lang.Thread.run(Thread.java:841)
I/MainActivity: Info:Closing /dev/bus/usb/001/049...
E/UsbDeviceConnectionJNI: device is closed in native_control_request
I/CDCSerialDevice: Control Transfer Response: -1
E/UsbDeviceConnectionJNI: device is closed in native_release_interface
D/UsbDeviceConnectionJNI: close
I/MainActivity: Info:Waiting for virtual port /dev/bus/usb/001/049 to disappear...
I/System.out: deviceKey:/dev/bus/usb/001/049-> UsbDevice[mName=/dev/bus/usb/001/049,mVendorId=9025,mProductId=32822,mClass=239,mSubclass=2,mProtocol=1,mInterfaces=[Landroid.os.Parcelable;@528d7dcc]
W/System.err: Exception during close of the programmer: 'Task java.util.concurrent.FutureTask@528ce46c rejected from java.util.concurrent.ThreadPoolExecutor@528a5a8c[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]'.
W/System.err:     at ArduinoUploader.BootloaderProgrammers.Protocols.AVR109.Avr109BootloaderProgrammer.Close(Avr109BootloaderProgrammer.java:49)
W/System.err:     at ArduinoUploader.ArduinoSketchUploader.UploadSketch(ArduinoSketchUploader.java:350)
W/System.err:     at xyz.vidieukhien.embedded.arduinohexuploadexample.MainActivity.uploadHex(MainActivity.java:320)
W/System.err:     at xyz.vidieukhien.embedded.arduinohexuploadexample.MainActivity$UploadRunnable.run(MainActivity.java:336)
W/System.err:     at java.lang.Thread.run(Thread.java:841)

**Comment by vospascal** [comment]
Yea I know it doesn’t work I read the code and tried some arduinos

**Comment by georgedrive** [comment]
there is one missed moment. I was forbidden to tell. if you fix it, then avr109 starts to work - arduino goes into programming mode, but the com.felhr.usbserial library gives an error and arduino immediately exits programming mode

**Comment by t2t-sonbui** [comment]
I see the port is change when upload. 
It means the port has been removed, then re-plugged. Fixing is not simple because on android os, usb will be automatically incremented every time it re-plugged( need request permission->change the port to correct new,...).

**Comment by t2t-sonbui** [comment]
Currently the repair procedure so it can have a chance to work is as follows:
With the protocol that the usb port is changed during bootloader activation(like for Leonardo board), the user must ask the user to grant the default permission for the application, then using with  only 1 usb device can be connected. During the process, always choose the first (and only) usb port to do it instead of its name.
I haven't had time to implement the code now nor have a board to test it with but this should help if you want to deploy early to fix yourself. Any pull request is always welcome.

**Comment by georgedrive** [comment]
file ArduinoUploader/BootloaderProgrammers/ResetBehavior/ResetThrough1200BpsBehavior.java



package ArduinoUploader.BootloaderProgrammers.ResetBehavior;

import android.content.Context;

import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

import ArduinoUploader.*;
import ArduinoUploader.BootloaderProgrammers.*;
import ArduinoUploader.Help.ISerialPortStream;
import ArduinoUploader.Help.SerialStreamHelper;

public class ResetThrough1200BpsBehavior<E extends ISerialPortStream> implements IResetBehavior {
    private static IArduinoUploaderLogger getLogger() {
        return ArduinoSketchUploader.getLogger();
    }

    private Class<E> inferedClass;
    private Context mContext;

    public ResetThrough1200BpsBehavior(Class<E> typeParameterClass, Context context) {
        this.inferedClass = typeParameterClass;
        this.mContext = context;
    }

    @Override
    public final ISerialPortStream Reset(ISerialPortStream serialPort, SerialPortConfig config) {
        final int timeoutVirtualPortDiscovery = 10000;
        final int virtualPortDiscoveryInterval = 100;
        if (getLogger() != null)
            getLogger().Info("Issuing forced 1200bps reset...");
        String currentPortName = serialPort.getPortName();
        String[] originalPorts = serialPort.getPortNames();
        // Close port ...
        serialPort.close();

        // And now open port at 1200 bps
        serialPort = SerialStreamHelper.newInstance(inferedClass, mContext, currentPortName, 1200);
        // new SerialPortStream(currentPortName, 1200);
        serialPort.setDtrEnable(true);
        serialPort.setRtsEnable(true);
        serialPort.open();
        // Close and wait for a new virtual COM port to appear ...
        serialPort.close();

        ISerialPortStream finalSerialPort = serialPort;
        String newPort = WaitHelper.WaitFor(timeoutVirtualPortDiscovery, virtualPortDiscoveryInterval,
                //() -> portSingleOrDefault,
                //() -> SerialPortStream.GetPortNames().Except(originalPorts).SingleOrDefault(),
                () -> {
                    // Remove duplicates from an array in Java [duplicate]
                    Set<String> ports = new HashSet<String>();
                    for (String port : finalSerialPort.getPortNames()) {
                        ports.add(port);
                        getLogger().Info("add: " + port);
                    }
                    // Except
                    Iterator<String> itr = ports.iterator();
                    while (itr.hasNext()) {
                        String sp = (String) itr.next();
                        for (String pt : originalPorts) {
                            if (sp.equals(pt))
                                itr.remove();
                        }
                    }
                    String[] uniquePorts = ports.toArray(new String[ports.size()]);
                    //final String portSingleOrDefault;
                    if (uniquePorts.length > 0) {
                        return uniquePorts[0];
                    } else
                        return null;
                },
                (i, item, interval) -> item == null ? String.format("T+%1$s - Port not found", i * interval)
                        : String.format("T+%1$s - Port found: %2$s", i * interval, item));

        if (newPort == null) {
            throw new ArduinoUploaderException(String
                    .format("No (unambiguous) virtual COM port detected (after %1$sms).", timeoutVirtualPortDiscovery));
        }

        E tempVar = SerialStreamHelper.newInstance(inferedClass, mContext, newPort, config.getBaudRate());
        // new SerialPortStream(newPort, config.getBaudRate());
        tempVar.setNumDataBits​(8);
        tempVar.setParity​(ISerialPortStream.NO_PARITY);
        tempVar.setNumStopBits​(ISerialPortStream.ONE_STOP_BIT);
        tempVar.setDtrEnable(true);
        tempVar.setRtsEnable(true);
        return tempVar;
    }

}



line
for (String port : finalSerialPort.getPortNames()) {
does not receive new ports is obtained. the logs show that the device has connected - a new port has appeared, and getPortNames only returns the old port. What to do?

**Comment by georgedrive** [comment]
Any hardware is possible as long as it uses the AVR109 protocol
